--- # https://developer.forecast.io/docs/v2
structure:
    currently: currently
    minutely:
        - 60
        - minutely
    hourly:
        - 48
        - hourly
    daily:
        - 7
        - daily
datablock:
    - summary
    - icon
currently:
    # all datapoints:
    - time
    - summary
    - icon
    - precipIntensity # +precipIntensityError
    - precipProbability # +precipProbabilityError
    - precipType
    - dewPoint # +dewPointError
    - windSpeed # +windSpeedError
    - windBearing #+windBearingError
    - cloudCover #+cloudCoverError
    - humidity #+humidityError
    - pressure #+pressureError
    - visibility #+visibilityError
    - ozone #+ozoneError
    # non-daily:
    - temperature #+temperatureError
    - apparentTemperature #+apparentTemperatureError
    # currently only:
    - nearestStormDistance #+nearestStormDistanceError
    - nearestStormBearing #+nearestStormBearingError
minutely:
    # all datapoints:
    - time
    - summary
    - icon
    - precipIntensity # +precipIntensityError
    - precipProbability # +precipProbabilityError
    - precipType
    - dewPoint # +dewPointError
    - windSpeed # +windSpeedError
    - windBearing #+windBearingError
    - cloudCover #+cloudCoverError
    - humidity #+humidityError
    - pressure #+pressureError
    - visibility #+visibilityError
    - ozone #+ozoneError
    # non-daily:
    - temperature #+temperatureError
    - apparentTemperature #+apparentTemperatureError
hourly:
    # all datapoints:
    - time
    - summary
    - icon
    - precipIntensity # +precipIntensityError
    - precipProbability # +precipProbabilityError
    - precipType
    - dewPoint # +dewPointError
    - windSpeed # +windSpeedError
    - windBearing #+windBearingError
    - cloudCover #+cloudCoverError
    - humidity #+humidityError
    - pressure #+pressureError
    - visibility #+visibilityError
    - ozone #+ozoneError
    # non-daily:
    - temperature #+temperatureError
    - apparentTemperature #+apparentTemperatureError
    # hourly or daily:
    - precipAccumulation #+precipAccumulationError
daily:
    # all datapoints:
    - time
    - summary
    - icon
    - precipIntensity # +precipIntensityError
    - precipProbability # +precipProbabilityError
    - precipType
    - dewPoint # +dewPointError
    - windSpeed # +windSpeedError
    - windBearing #+windBearingError
    - cloudCover #+cloudCoverError
    - humidity #+humidityError
    - pressure #+pressureError
    - visibility #+visibilityError
    - ozone #+ozoneError
    # hourly or daily:
    - precipAccumulation #+precipAccumulationError
    # daily only:
    - sunriseTime
    - sunsetTime
    - moonPhase
    - precipIntensityMax #+precipIntensityMaxError
    - precipIntensityMaxTime
    - temperatureMin #+temperatureMinError
    - temperatureMinTime
    - temperatureMax #+temperatureMaxError
    - temperatureMaxTime
    - apparentTemperatureMin #+apparentTemperatureMinError
    - apparentTemperatureMinTime
    - apparentTemperatureMax #+apparentTemperatureMaxError
    - apparentTemperatureMaxTime
alerts:
    - title
    - expires
    - description
    - uri
flags:
    - darksky-unavailable
    - darksky-stations
    - isd-stations
    - lamp-stations
    - metar-stations
    - metno-license
    - sources
    - units
